// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: jwt-srv/jwt.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// JwtServiceClient is the client API for JwtService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JwtServiceClient interface {
	GenerateJWT(ctx context.Context, in *TokenBody, opts ...grpc.CallOption) (*Token, error)
	DecodeJWT(ctx context.Context, in *Token, opts ...grpc.CallOption) (*DecodeResp, error)
}

type jwtServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJwtServiceClient(cc grpc.ClientConnInterface) JwtServiceClient {
	return &jwtServiceClient{cc}
}

func (c *jwtServiceClient) GenerateJWT(ctx context.Context, in *TokenBody, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/pp.jwt.JwtService/GenerateJWT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jwtServiceClient) DecodeJWT(ctx context.Context, in *Token, opts ...grpc.CallOption) (*DecodeResp, error) {
	out := new(DecodeResp)
	err := c.cc.Invoke(ctx, "/pp.jwt.JwtService/DecodeJWT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JwtServiceServer is the server API for JwtService service.
// All implementations must embed UnimplementedJwtServiceServer
// for forward compatibility
type JwtServiceServer interface {
	GenerateJWT(context.Context, *TokenBody) (*Token, error)
	DecodeJWT(context.Context, *Token) (*DecodeResp, error)
	mustEmbedUnimplementedJwtServiceServer()
}

// UnimplementedJwtServiceServer must be embedded to have forward compatible implementations.
type UnimplementedJwtServiceServer struct {
}

func (UnimplementedJwtServiceServer) GenerateJWT(context.Context, *TokenBody) (*Token, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateJWT not implemented")
}
func (UnimplementedJwtServiceServer) DecodeJWT(context.Context, *Token) (*DecodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecodeJWT not implemented")
}
func (UnimplementedJwtServiceServer) mustEmbedUnimplementedJwtServiceServer() {}

// UnsafeJwtServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JwtServiceServer will
// result in compilation errors.
type UnsafeJwtServiceServer interface {
	mustEmbedUnimplementedJwtServiceServer()
}

func RegisterJwtServiceServer(s grpc.ServiceRegistrar, srv JwtServiceServer) {
	s.RegisterService(&JwtService_ServiceDesc, srv)
}

func _JwtService_GenerateJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenBody)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JwtServiceServer).GenerateJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pp.jwt.JwtService/GenerateJWT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JwtServiceServer).GenerateJWT(ctx, req.(*TokenBody))
	}
	return interceptor(ctx, in, info, handler)
}

func _JwtService_DecodeJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JwtServiceServer).DecodeJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pp.jwt.JwtService/DecodeJWT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JwtServiceServer).DecodeJWT(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

// JwtService_ServiceDesc is the grpc.ServiceDesc for JwtService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JwtService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pp.jwt.JwtService",
	HandlerType: (*JwtServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateJWT",
			Handler:    _JwtService_GenerateJWT_Handler,
		},
		{
			MethodName: "DecodeJWT",
			Handler:    _JwtService_DecodeJWT_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jwt-srv/jwt.proto",
}
